/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialMediaMarketingForRestaurantsMumbaiRouteImport } from './routes/social-media-marketing-for-restaurants-mumbai'
import { Route as SocialMediaMarketingCostMumbaiRouteImport } from './routes/social-media-marketing-cost-mumbai'
import { Route as SocialMediaAgencyVsInhouseVsFreelancerMumbaiRouteImport } from './routes/social-media-agency-vs-inhouse-vs-freelancer-mumbai'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as InstagramMarketingAgencyMumbaiGuideRouteImport } from './routes/instagram-marketing-agency-mumbai-guide'
import { Route as HowToChooseSocialMediaAgencyMumbaiRouteImport } from './routes/how-to-choose-social-media-agency-mumbai'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWhatsappMarketingMumbaiRouteImport } from './routes/services.whatsapp-marketing-mumbai'
import { Route as ServicesWebsiteDevelopmentMumbaiRouteImport } from './routes/services.website-development-mumbai'
import { Route as ServicesSocialMediaMarketingMumbaiRouteImport } from './routes/services.social-media-marketing-mumbai'
import { Route as ServicesMetaAdsManagementMumbaiRouteImport } from './routes/services.meta-ads-management-mumbai'
import { Route as ServicesInstagramMarketingMumbaiRouteImport } from './routes/services.instagram-marketing-mumbai'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'

const SocialMediaMarketingForRestaurantsMumbaiRoute =
  SocialMediaMarketingForRestaurantsMumbaiRouteImport.update({
    id: '/social-media-marketing-for-restaurants-mumbai',
    path: '/social-media-marketing-for-restaurants-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const SocialMediaMarketingCostMumbaiRoute =
  SocialMediaMarketingCostMumbaiRouteImport.update({
    id: '/social-media-marketing-cost-mumbai',
    path: '/social-media-marketing-cost-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const SocialMediaAgencyVsInhouseVsFreelancerMumbaiRoute =
  SocialMediaAgencyVsInhouseVsFreelancerMumbaiRouteImport.update({
    id: '/social-media-agency-vs-inhouse-vs-freelancer-mumbai',
    path: '/social-media-agency-vs-inhouse-vs-freelancer-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramMarketingAgencyMumbaiGuideRoute =
  InstagramMarketingAgencyMumbaiGuideRouteImport.update({
    id: '/instagram-marketing-agency-mumbai-guide',
    path: '/instagram-marketing-agency-mumbai-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowToChooseSocialMediaAgencyMumbaiRoute =
  HowToChooseSocialMediaAgencyMumbaiRouteImport.update({
    id: '/how-to-choose-social-media-agency-mumbai',
    path: '/how-to-choose-social-media-agency-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWhatsappMarketingMumbaiRoute =
  ServicesWhatsappMarketingMumbaiRouteImport.update({
    id: '/services/whatsapp-marketing-mumbai',
    path: '/services/whatsapp-marketing-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWebsiteDevelopmentMumbaiRoute =
  ServicesWebsiteDevelopmentMumbaiRouteImport.update({
    id: '/services/website-development-mumbai',
    path: '/services/website-development-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSocialMediaMarketingMumbaiRoute =
  ServicesSocialMediaMarketingMumbaiRouteImport.update({
    id: '/services/social-media-marketing-mumbai',
    path: '/services/social-media-marketing-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMetaAdsManagementMumbaiRoute =
  ServicesMetaAdsManagementMumbaiRouteImport.update({
    id: '/services/meta-ads-management-mumbai',
    path: '/services/meta-ads-management-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInstagramMarketingMumbaiRoute =
  ServicesInstagramMarketingMumbaiRouteImport.update({
    id: '/services/instagram-marketing-mumbai',
    path: '/services/instagram-marketing-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/how-to-choose-social-media-agency-mumbai': typeof HowToChooseSocialMediaAgencyMumbaiRoute
  '/instagram-marketing-agency-mumbai-guide': typeof InstagramMarketingAgencyMumbaiGuideRoute
  '/packages': typeof PackagesRoute
  '/social-media-agency-vs-inhouse-vs-freelancer-mumbai': typeof SocialMediaAgencyVsInhouseVsFreelancerMumbaiRoute
  '/social-media-marketing-cost-mumbai': typeof SocialMediaMarketingCostMumbaiRoute
  '/social-media-marketing-for-restaurants-mumbai': typeof SocialMediaMarketingForRestaurantsMumbaiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/instagram-marketing-mumbai': typeof ServicesInstagramMarketingMumbaiRoute
  '/services/meta-ads-management-mumbai': typeof ServicesMetaAdsManagementMumbaiRoute
  '/services/social-media-marketing-mumbai': typeof ServicesSocialMediaMarketingMumbaiRoute
  '/services/website-development-mumbai': typeof ServicesWebsiteDevelopmentMumbaiRoute
  '/services/whatsapp-marketing-mumbai': typeof ServicesWhatsappMarketingMumbaiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/how-to-choose-social-media-agency-mumbai': typeof HowToChooseSocialMediaAgencyMumbaiRoute
  '/instagram-marketing-agency-mumbai-guide': typeof InstagramMarketingAgencyMumbaiGuideRoute
  '/packages': typeof PackagesRoute
  '/social-media-agency-vs-inhouse-vs-freelancer-mumbai': typeof SocialMediaAgencyVsInhouseVsFreelancerMumbaiRoute
  '/social-media-marketing-cost-mumbai': typeof SocialMediaMarketingCostMumbaiRoute
  '/social-media-marketing-for-restaurants-mumbai': typeof SocialMediaMarketingForRestaurantsMumbaiRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/instagram-marketing-mumbai': typeof ServicesInstagramMarketingMumbaiRoute
  '/services/meta-ads-management-mumbai': typeof ServicesMetaAdsManagementMumbaiRoute
  '/services/social-media-marketing-mumbai': typeof ServicesSocialMediaMarketingMumbaiRoute
  '/services/website-development-mumbai': typeof ServicesWebsiteDevelopmentMumbaiRoute
  '/services/whatsapp-marketing-mumbai': typeof ServicesWhatsappMarketingMumbaiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/how-to-choose-social-media-agency-mumbai': typeof HowToChooseSocialMediaAgencyMumbaiRoute
  '/instagram-marketing-agency-mumbai-guide': typeof InstagramMarketingAgencyMumbaiGuideRoute
  '/packages': typeof PackagesRoute
  '/social-media-agency-vs-inhouse-vs-freelancer-mumbai': typeof SocialMediaAgencyVsInhouseVsFreelancerMumbaiRoute
  '/social-media-marketing-cost-mumbai': typeof SocialMediaMarketingCostMumbaiRoute
  '/social-media-marketing-for-restaurants-mumbai': typeof SocialMediaMarketingForRestaurantsMumbaiRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/services/instagram-marketing-mumbai': typeof ServicesInstagramMarketingMumbaiRoute
  '/services/meta-ads-management-mumbai': typeof ServicesMetaAdsManagementMumbaiRoute
  '/services/social-media-marketing-mumbai': typeof ServicesSocialMediaMarketingMumbaiRoute
  '/services/website-development-mumbai': typeof ServicesWebsiteDevelopmentMumbaiRoute
  '/services/whatsapp-marketing-mumbai': typeof ServicesWhatsappMarketingMumbaiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/how-to-choose-social-media-agency-mumbai'
    | '/instagram-marketing-agency-mumbai-guide'
    | '/packages'
    | '/social-media-agency-vs-inhouse-vs-freelancer-mumbai'
    | '/social-media-marketing-cost-mumbai'
    | '/social-media-marketing-for-restaurants-mumbai'
    | '/blog/$slug'
    | '/services/instagram-marketing-mumbai'
    | '/services/meta-ads-management-mumbai'
    | '/services/social-media-marketing-mumbai'
    | '/services/website-development-mumbai'
    | '/services/whatsapp-marketing-mumbai'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/how-to-choose-social-media-agency-mumbai'
    | '/instagram-marketing-agency-mumbai-guide'
    | '/packages'
    | '/social-media-agency-vs-inhouse-vs-freelancer-mumbai'
    | '/social-media-marketing-cost-mumbai'
    | '/social-media-marketing-for-restaurants-mumbai'
    | '/blog/$slug'
    | '/services/instagram-marketing-mumbai'
    | '/services/meta-ads-management-mumbai'
    | '/services/social-media-marketing-mumbai'
    | '/services/website-development-mumbai'
    | '/services/whatsapp-marketing-mumbai'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/how-to-choose-social-media-agency-mumbai'
    | '/instagram-marketing-agency-mumbai-guide'
    | '/packages'
    | '/social-media-agency-vs-inhouse-vs-freelancer-mumbai'
    | '/social-media-marketing-cost-mumbai'
    | '/social-media-marketing-for-restaurants-mumbai'
    | '/blog_/$slug'
    | '/services/instagram-marketing-mumbai'
    | '/services/meta-ads-management-mumbai'
    | '/services/social-media-marketing-mumbai'
    | '/services/website-development-mumbai'
    | '/services/whatsapp-marketing-mumbai'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  HowToChooseSocialMediaAgencyMumbaiRoute: typeof HowToChooseSocialMediaAgencyMumbaiRoute
  InstagramMarketingAgencyMumbaiGuideRoute: typeof InstagramMarketingAgencyMumbaiGuideRoute
  PackagesRoute: typeof PackagesRoute
  SocialMediaAgencyVsInhouseVsFreelancerMumbaiRoute: typeof SocialMediaAgencyVsInhouseVsFreelancerMumbaiRoute
  SocialMediaMarketingCostMumbaiRoute: typeof SocialMediaMarketingCostMumbaiRoute
  SocialMediaMarketingForRestaurantsMumbaiRoute: typeof SocialMediaMarketingForRestaurantsMumbaiRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicesInstagramMarketingMumbaiRoute: typeof ServicesInstagramMarketingMumbaiRoute
  ServicesMetaAdsManagementMumbaiRoute: typeof ServicesMetaAdsManagementMumbaiRoute
  ServicesSocialMediaMarketingMumbaiRoute: typeof ServicesSocialMediaMarketingMumbaiRoute
  ServicesWebsiteDevelopmentMumbaiRoute: typeof ServicesWebsiteDevelopmentMumbaiRoute
  ServicesWhatsappMarketingMumbaiRoute: typeof ServicesWhatsappMarketingMumbaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social-media-marketing-for-restaurants-mumbai': {
      id: '/social-media-marketing-for-restaurants-mumbai'
      path: '/social-media-marketing-for-restaurants-mumbai'
      fullPath: '/social-media-marketing-for-restaurants-mumbai'
      preLoaderRoute: typeof SocialMediaMarketingForRestaurantsMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-marketing-cost-mumbai': {
      id: '/social-media-marketing-cost-mumbai'
      path: '/social-media-marketing-cost-mumbai'
      fullPath: '/social-media-marketing-cost-mumbai'
      preLoaderRoute: typeof SocialMediaMarketingCostMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-agency-vs-inhouse-vs-freelancer-mumbai': {
      id: '/social-media-agency-vs-inhouse-vs-freelancer-mumbai'
      path: '/social-media-agency-vs-inhouse-vs-freelancer-mumbai'
      fullPath: '/social-media-agency-vs-inhouse-vs-freelancer-mumbai'
      preLoaderRoute: typeof SocialMediaAgencyVsInhouseVsFreelancerMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram-marketing-agency-mumbai-guide': {
      id: '/instagram-marketing-agency-mumbai-guide'
      path: '/instagram-marketing-agency-mumbai-guide'
      fullPath: '/instagram-marketing-agency-mumbai-guide'
      preLoaderRoute: typeof InstagramMarketingAgencyMumbaiGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-choose-social-media-agency-mumbai': {
      id: '/how-to-choose-social-media-agency-mumbai'
      path: '/how-to-choose-social-media-agency-mumbai'
      fullPath: '/how-to-choose-social-media-agency-mumbai'
      preLoaderRoute: typeof HowToChooseSocialMediaAgencyMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/whatsapp-marketing-mumbai': {
      id: '/services/whatsapp-marketing-mumbai'
      path: '/services/whatsapp-marketing-mumbai'
      fullPath: '/services/whatsapp-marketing-mumbai'
      preLoaderRoute: typeof ServicesWhatsappMarketingMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-development-mumbai': {
      id: '/services/website-development-mumbai'
      path: '/services/website-development-mumbai'
      fullPath: '/services/website-development-mumbai'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media-marketing-mumbai': {
      id: '/services/social-media-marketing-mumbai'
      path: '/services/social-media-marketing-mumbai'
      fullPath: '/services/social-media-marketing-mumbai'
      preLoaderRoute: typeof ServicesSocialMediaMarketingMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/meta-ads-management-mumbai': {
      id: '/services/meta-ads-management-mumbai'
      path: '/services/meta-ads-management-mumbai'
      fullPath: '/services/meta-ads-management-mumbai'
      preLoaderRoute: typeof ServicesMetaAdsManagementMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/instagram-marketing-mumbai': {
      id: '/services/instagram-marketing-mumbai'
      path: '/services/instagram-marketing-mumbai'
      fullPath: '/services/instagram-marketing-mumbai'
      preLoaderRoute: typeof ServicesInstagramMarketingMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  HowToChooseSocialMediaAgencyMumbaiRoute:
    HowToChooseSocialMediaAgencyMumbaiRoute,
  InstagramMarketingAgencyMumbaiGuideRoute:
    InstagramMarketingAgencyMumbaiGuideRoute,
  PackagesRoute: PackagesRoute,
  SocialMediaAgencyVsInhouseVsFreelancerMumbaiRoute:
    SocialMediaAgencyVsInhouseVsFreelancerMumbaiRoute,
  SocialMediaMarketingCostMumbaiRoute: SocialMediaMarketingCostMumbaiRoute,
  SocialMediaMarketingForRestaurantsMumbaiRoute:
    SocialMediaMarketingForRestaurantsMumbaiRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicesInstagramMarketingMumbaiRoute: ServicesInstagramMarketingMumbaiRoute,
  ServicesMetaAdsManagementMumbaiRoute: ServicesMetaAdsManagementMumbaiRoute,
  ServicesSocialMediaMarketingMumbaiRoute:
    ServicesSocialMediaMarketingMumbaiRoute,
  ServicesWebsiteDevelopmentMumbaiRoute: ServicesWebsiteDevelopmentMumbaiRoute,
  ServicesWhatsappMarketingMumbaiRoute: ServicesWhatsappMarketingMumbaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
