/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWhatsappMarketingMumbaiRouteImport } from './routes/services.whatsapp-marketing-mumbai'
import { Route as ServicesWebsiteDevelopmentMumbaiRouteImport } from './routes/services.website-development-mumbai'
import { Route as ServicesSocialMediaMarketingMumbaiRouteImport } from './routes/services.social-media-marketing-mumbai'
import { Route as ServicesMetaAdsManagementMumbaiRouteImport } from './routes/services.meta-ads-management-mumbai'
import { Route as ServicesInstagramMarketingMumbaiRouteImport } from './routes/services.instagram-marketing-mumbai'
import { Route as PortfolioWebsitesRouteImport } from './routes/portfolio.websites'
import { Route as PortfolioVideoContentRouteImport } from './routes/portfolio.video-content'
import { Route as PortfolioAdCreativesRouteImport } from './routes/portfolio.ad-creatives'
import { Route as PortfolioVideoContentIndustryRouteImport } from './routes/portfolio.video-content.$industry'
import { Route as PortfolioAdCreativesIndustryRouteImport } from './routes/portfolio.ad-creatives.$industry'

const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWhatsappMarketingMumbaiRoute =
  ServicesWhatsappMarketingMumbaiRouteImport.update({
    id: '/services/whatsapp-marketing-mumbai',
    path: '/services/whatsapp-marketing-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWebsiteDevelopmentMumbaiRoute =
  ServicesWebsiteDevelopmentMumbaiRouteImport.update({
    id: '/services/website-development-mumbai',
    path: '/services/website-development-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSocialMediaMarketingMumbaiRoute =
  ServicesSocialMediaMarketingMumbaiRouteImport.update({
    id: '/services/social-media-marketing-mumbai',
    path: '/services/social-media-marketing-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesMetaAdsManagementMumbaiRoute =
  ServicesMetaAdsManagementMumbaiRouteImport.update({
    id: '/services/meta-ads-management-mumbai',
    path: '/services/meta-ads-management-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesInstagramMarketingMumbaiRoute =
  ServicesInstagramMarketingMumbaiRouteImport.update({
    id: '/services/instagram-marketing-mumbai',
    path: '/services/instagram-marketing-mumbai',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortfolioWebsitesRoute = PortfolioWebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioVideoContentRoute = PortfolioVideoContentRouteImport.update({
  id: '/video-content',
  path: '/video-content',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioAdCreativesRoute = PortfolioAdCreativesRouteImport.update({
  id: '/ad-creatives',
  path: '/ad-creatives',
  getParentRoute: () => PortfolioRoute,
} as any)
const PortfolioVideoContentIndustryRoute =
  PortfolioVideoContentIndustryRouteImport.update({
    id: '/$industry',
    path: '/$industry',
    getParentRoute: () => PortfolioVideoContentRoute,
  } as any)
const PortfolioAdCreativesIndustryRoute =
  PortfolioAdCreativesIndustryRouteImport.update({
    id: '/$industry',
    path: '/$industry',
    getParentRoute: () => PortfolioAdCreativesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/portfolio/ad-creatives': typeof PortfolioAdCreativesRouteWithChildren
  '/portfolio/video-content': typeof PortfolioVideoContentRouteWithChildren
  '/portfolio/websites': typeof PortfolioWebsitesRoute
  '/services/instagram-marketing-mumbai': typeof ServicesInstagramMarketingMumbaiRoute
  '/services/meta-ads-management-mumbai': typeof ServicesMetaAdsManagementMumbaiRoute
  '/services/social-media-marketing-mumbai': typeof ServicesSocialMediaMarketingMumbaiRoute
  '/services/website-development-mumbai': typeof ServicesWebsiteDevelopmentMumbaiRoute
  '/services/whatsapp-marketing-mumbai': typeof ServicesWhatsappMarketingMumbaiRoute
  '/portfolio/ad-creatives/$industry': typeof PortfolioAdCreativesIndustryRoute
  '/portfolio/video-content/$industry': typeof PortfolioVideoContentIndustryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/portfolio/ad-creatives': typeof PortfolioAdCreativesRouteWithChildren
  '/portfolio/video-content': typeof PortfolioVideoContentRouteWithChildren
  '/portfolio/websites': typeof PortfolioWebsitesRoute
  '/services/instagram-marketing-mumbai': typeof ServicesInstagramMarketingMumbaiRoute
  '/services/meta-ads-management-mumbai': typeof ServicesMetaAdsManagementMumbaiRoute
  '/services/social-media-marketing-mumbai': typeof ServicesSocialMediaMarketingMumbaiRoute
  '/services/website-development-mumbai': typeof ServicesWebsiteDevelopmentMumbaiRoute
  '/services/whatsapp-marketing-mumbai': typeof ServicesWhatsappMarketingMumbaiRoute
  '/portfolio/ad-creatives/$industry': typeof PortfolioAdCreativesIndustryRoute
  '/portfolio/video-content/$industry': typeof PortfolioVideoContentIndustryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/packages': typeof PackagesRoute
  '/portfolio': typeof PortfolioRouteWithChildren
  '/portfolio/ad-creatives': typeof PortfolioAdCreativesRouteWithChildren
  '/portfolio/video-content': typeof PortfolioVideoContentRouteWithChildren
  '/portfolio/websites': typeof PortfolioWebsitesRoute
  '/services/instagram-marketing-mumbai': typeof ServicesInstagramMarketingMumbaiRoute
  '/services/meta-ads-management-mumbai': typeof ServicesMetaAdsManagementMumbaiRoute
  '/services/social-media-marketing-mumbai': typeof ServicesSocialMediaMarketingMumbaiRoute
  '/services/website-development-mumbai': typeof ServicesWebsiteDevelopmentMumbaiRoute
  '/services/whatsapp-marketing-mumbai': typeof ServicesWhatsappMarketingMumbaiRoute
  '/portfolio/ad-creatives/$industry': typeof PortfolioAdCreativesIndustryRoute
  '/portfolio/video-content/$industry': typeof PortfolioVideoContentIndustryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/contact'
    | '/packages'
    | '/portfolio'
    | '/portfolio/ad-creatives'
    | '/portfolio/video-content'
    | '/portfolio/websites'
    | '/services/instagram-marketing-mumbai'
    | '/services/meta-ads-management-mumbai'
    | '/services/social-media-marketing-mumbai'
    | '/services/website-development-mumbai'
    | '/services/whatsapp-marketing-mumbai'
    | '/portfolio/ad-creatives/$industry'
    | '/portfolio/video-content/$industry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contact'
    | '/packages'
    | '/portfolio'
    | '/portfolio/ad-creatives'
    | '/portfolio/video-content'
    | '/portfolio/websites'
    | '/services/instagram-marketing-mumbai'
    | '/services/meta-ads-management-mumbai'
    | '/services/social-media-marketing-mumbai'
    | '/services/website-development-mumbai'
    | '/services/whatsapp-marketing-mumbai'
    | '/portfolio/ad-creatives/$industry'
    | '/portfolio/video-content/$industry'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/contact'
    | '/packages'
    | '/portfolio'
    | '/portfolio/ad-creatives'
    | '/portfolio/video-content'
    | '/portfolio/websites'
    | '/services/instagram-marketing-mumbai'
    | '/services/meta-ads-management-mumbai'
    | '/services/social-media-marketing-mumbai'
    | '/services/website-development-mumbai'
    | '/services/whatsapp-marketing-mumbai'
    | '/portfolio/ad-creatives/$industry'
    | '/portfolio/video-content/$industry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  PackagesRoute: typeof PackagesRoute
  PortfolioRoute: typeof PortfolioRouteWithChildren
  ServicesInstagramMarketingMumbaiRoute: typeof ServicesInstagramMarketingMumbaiRoute
  ServicesMetaAdsManagementMumbaiRoute: typeof ServicesMetaAdsManagementMumbaiRoute
  ServicesSocialMediaMarketingMumbaiRoute: typeof ServicesSocialMediaMarketingMumbaiRoute
  ServicesWebsiteDevelopmentMumbaiRoute: typeof ServicesWebsiteDevelopmentMumbaiRoute
  ServicesWhatsappMarketingMumbaiRoute: typeof ServicesWhatsappMarketingMumbaiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/whatsapp-marketing-mumbai': {
      id: '/services/whatsapp-marketing-mumbai'
      path: '/services/whatsapp-marketing-mumbai'
      fullPath: '/services/whatsapp-marketing-mumbai'
      preLoaderRoute: typeof ServicesWhatsappMarketingMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-development-mumbai': {
      id: '/services/website-development-mumbai'
      path: '/services/website-development-mumbai'
      fullPath: '/services/website-development-mumbai'
      preLoaderRoute: typeof ServicesWebsiteDevelopmentMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media-marketing-mumbai': {
      id: '/services/social-media-marketing-mumbai'
      path: '/services/social-media-marketing-mumbai'
      fullPath: '/services/social-media-marketing-mumbai'
      preLoaderRoute: typeof ServicesSocialMediaMarketingMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/meta-ads-management-mumbai': {
      id: '/services/meta-ads-management-mumbai'
      path: '/services/meta-ads-management-mumbai'
      fullPath: '/services/meta-ads-management-mumbai'
      preLoaderRoute: typeof ServicesMetaAdsManagementMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/instagram-marketing-mumbai': {
      id: '/services/instagram-marketing-mumbai'
      path: '/services/instagram-marketing-mumbai'
      fullPath: '/services/instagram-marketing-mumbai'
      preLoaderRoute: typeof ServicesInstagramMarketingMumbaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/websites': {
      id: '/portfolio/websites'
      path: '/websites'
      fullPath: '/portfolio/websites'
      preLoaderRoute: typeof PortfolioWebsitesRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/video-content': {
      id: '/portfolio/video-content'
      path: '/video-content'
      fullPath: '/portfolio/video-content'
      preLoaderRoute: typeof PortfolioVideoContentRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/ad-creatives': {
      id: '/portfolio/ad-creatives'
      path: '/ad-creatives'
      fullPath: '/portfolio/ad-creatives'
      preLoaderRoute: typeof PortfolioAdCreativesRouteImport
      parentRoute: typeof PortfolioRoute
    }
    '/portfolio/video-content/$industry': {
      id: '/portfolio/video-content/$industry'
      path: '/$industry'
      fullPath: '/portfolio/video-content/$industry'
      preLoaderRoute: typeof PortfolioVideoContentIndustryRouteImport
      parentRoute: typeof PortfolioVideoContentRoute
    }
    '/portfolio/ad-creatives/$industry': {
      id: '/portfolio/ad-creatives/$industry'
      path: '/$industry'
      fullPath: '/portfolio/ad-creatives/$industry'
      preLoaderRoute: typeof PortfolioAdCreativesIndustryRouteImport
      parentRoute: typeof PortfolioAdCreativesRoute
    }
  }
}

interface PortfolioAdCreativesRouteChildren {
  PortfolioAdCreativesIndustryRoute: typeof PortfolioAdCreativesIndustryRoute
}

const PortfolioAdCreativesRouteChildren: PortfolioAdCreativesRouteChildren = {
  PortfolioAdCreativesIndustryRoute: PortfolioAdCreativesIndustryRoute,
}

const PortfolioAdCreativesRouteWithChildren =
  PortfolioAdCreativesRoute._addFileChildren(PortfolioAdCreativesRouteChildren)

interface PortfolioVideoContentRouteChildren {
  PortfolioVideoContentIndustryRoute: typeof PortfolioVideoContentIndustryRoute
}

const PortfolioVideoContentRouteChildren: PortfolioVideoContentRouteChildren = {
  PortfolioVideoContentIndustryRoute: PortfolioVideoContentIndustryRoute,
}

const PortfolioVideoContentRouteWithChildren =
  PortfolioVideoContentRoute._addFileChildren(
    PortfolioVideoContentRouteChildren,
  )

interface PortfolioRouteChildren {
  PortfolioAdCreativesRoute: typeof PortfolioAdCreativesRouteWithChildren
  PortfolioVideoContentRoute: typeof PortfolioVideoContentRouteWithChildren
  PortfolioWebsitesRoute: typeof PortfolioWebsitesRoute
}

const PortfolioRouteChildren: PortfolioRouteChildren = {
  PortfolioAdCreativesRoute: PortfolioAdCreativesRouteWithChildren,
  PortfolioVideoContentRoute: PortfolioVideoContentRouteWithChildren,
  PortfolioWebsitesRoute: PortfolioWebsitesRoute,
}

const PortfolioRouteWithChildren = PortfolioRoute._addFileChildren(
  PortfolioRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  PackagesRoute: PackagesRoute,
  PortfolioRoute: PortfolioRouteWithChildren,
  ServicesInstagramMarketingMumbaiRoute: ServicesInstagramMarketingMumbaiRoute,
  ServicesMetaAdsManagementMumbaiRoute: ServicesMetaAdsManagementMumbaiRoute,
  ServicesSocialMediaMarketingMumbaiRoute:
    ServicesSocialMediaMarketingMumbaiRoute,
  ServicesWebsiteDevelopmentMumbaiRoute: ServicesWebsiteDevelopmentMumbaiRoute,
  ServicesWhatsappMarketingMumbaiRoute: ServicesWhatsappMarketingMumbaiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
